### ISSUE TITLE
最後の決済処理でエラー

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/SPAFT#10]
下記のエラーが出た
```
2024-08-12 14:46:51,040 (268)  [INFO] 保有株情報チェック処理開始 [trade.py in 685]
2024-08-12 14:46:51,048 (268)  [INFO] {'CashMargin': 2, 'MarginTradeType': 3, 'MarginPremium': None, 'ID': 'xxx', 'State': 1, 'OrderState': 1, 'OrdType': 1, 'RecvTime': '2024-08-12T14:44:40.6185243+09:00', 'Symbol': '1570', 'SymbolName': 'ＮＥＸＴ\u3000ＦＵＮＤＳ\u3000日経平均レバレッジ・インデックス連動型上場投信', 'Exchange': 1, 'ExchangeName': '東証ETF/ETN', 'Price': 21955.0, 'OrderQty': 1.0, 'CumQty': 0.0, 'Side': '2', 'AccountType': 4, 'DelivType': 0, 'ExpireDay': 20240813, 'Details': [{'SeqNum': 1, 'ID': 'xxx', 'RecType': 1, 'ExchangeID': None, 'State': 3, 'TransactTime': '2024-08-12T14:44:40.6185243+09:00', 'OrdType': 1, 'Price': 21955.0, 'Qty': 1.0, 'ExecutionID': None, 'ExecutionDay': None, 'DelivDay': 20240815, 'Commission': 0.0, 'CommissionTax': 0.0}, {'SeqNum': 2, 'ID': '20240812B01N44511581', 'RecType': 4, 'ExchangeID': None, 'State': 1, 'TransactTime': '2024-08-12T14:44:40.6185243+09:00', 'OrdType': 1, 'Price': 21955.0, 'Qty': 1.0, 'ExecutionID': None, 'ExecutionDay': None, 'DelivDay': 20240815, 'Commission': 0.0, 'CommissionTax': 0.0}]} [trade.py in 691]
Traceback (most recent call last):
  File "C:\Users\test\SPAFT\src\main.py", line 35, in <module>
    m.main()
  File "C:\Users\test\SPAFT\src\main.py", line 29, in main
    self.logic.scalping()
  File "C:\Users\test\SPAFT\src\service\trade.py", line 238, in scalping
    self.enforce_management(trade_type = '取引全体終了設定時間越え')
  File "C:\Users\test\SPAFT\src\service\trade.py", line 749, in enforce_management
    result, order_flag = self.enforce_settlement(trade_password)
  File "C:\Users\test\SPAFT\src\service\trade.py", line 694, in enforce_settlement
    qty = order['LeavesQty'] - order['HoldQty']
KeyError: 'LeavesQty'
```

**Comment by poi-ai** [comment]
LeavesQty、HoldQtyそれぞれのキーをチェックする処理を追加して一旦修正完了。

**Comment by poi-ai** [comment]
2024-08-15稼働ではエラーが発生しなかったのでクローズ。
問題出たらまた再度開く
