### ISSUE TITLE
板情報のCSVから有名な指標をカラムとして追加する

### ISSUE THREAD

**Issue by poi-ai** [poi-ai/SPAFT#20]
#19 で作成した板情報をKabus APIから出力したCSVを用いて、移動平均線やRSIなどテクニカルで著名な指標を算出し、CSVの新たなカラムを追加する

**Comment by poi-ai** [comment]
3種類の移動平均線算出・カラム追加処理は完成
あと他の指標としては、
* ボリンジャーバンド
* MACD
* RSI
* DMI
* 一目均衡表
* パラボリック
* サイコロジカルライン

ここらへんかな
使えなさそうな指標もありそうだけど、実際に機械学習でデータを飲ませると重要度の高い(精度を上げるのに有用な)説明変数だったということもよくあるので、集める段階では広く集めるようにしておく
実際使えなかったら除外すればいいだけだし

**Comment by poi-ai** [comment]
DMIだけは高値と終値が絶対に必要になるから、今の取得処理(1回/分)ではチェックできないということで今回実装は見送り。
それ以外のデータは実装完了
12/30のデータで出力させてみたけど、パラボリック以外はOK
パラボリックは見直しが必要かも

**Comment by poi-ai** [comment]
パラボリックの計算が狂っていたのでそこの修正と、目的変数候補のx分後の増減額・増減率・増減フラグを計算してカラム追加する処理の実装を行った

**Comment by poi-ai** [comment]
とりあえずは↑でコミットしたコードのみで説明変数用カラムの追加は終了。あとはバグ直しだけ

今出てるエラー

```
2025-01-15 00:05:18,909 (10316)  [ERROR] SAR計算でエラー
('sar_1min_0.01_0.1af', 'sar_1min_0.01_0.1af_flag')
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('sar_1min_0.01_0.1af', 'sar_1min_0.01_0.1af_flag')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Desktop\git\SPAFT\src\util\indicator.py", line 605, in get_parabolic
    df = df.merge(df_resampled[column_name, column_name_flag], left_index=True, right_index=True, how='left')
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 3506, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: ('sar_1min_0.01_0.1af', 'sar_1min_0.01_0.1af_flag')
 [indicator.py in 612]
```

**Comment by poi-ai** [comment]
取引を行う状態が揃うまでは一旦保留。

-----------

忘れないようにメモ

APIからNOWの板情報からデータ取得 ( #19 ) → そのデータからテクニカル指標の追加 (これ)
過去の分足情報を取得( #22 ) → そのデータからテクニカル指標を追加( #23 、これをベースに作成)

* APIからだと普通に全注文が取得できないので、PUSH通知でほぼ全部受けられるように変更( #21 )(ただこれでも400msごとなので一部は漏れる)
* 注文医系以外の処理(板情報取得)はPUSHをベースに作り直すと思うので、こっちも併せて作り直す予定
* ただ #23 の処理を崩さないように作る必要がある

その前に予測モデルが必要になるのでそっちを作ってから
